### PR TITLE
Makes `to` and `from` into namespaces with a nested `json` command

### LINKED ISSUE #36: No newline after each stream written by `ion dump -f pretty`
Related to amzn/ion-rust#437.

When dumping multiple input files, the missing trailing newline causes the last and first values in successive streams to run together, modifying the data or producing illegal syntax.

image

Note that the `3` at the end of each stream and the `1` of the next stream are concatenated to form legal-but-wrong `31`s.

### PR DESCRIPTION
**Pull request by zslayton**
Prior to this PR, `to` and `from` were commands that each took a `format`
flag that could be used to specify `json`. This patch promotes `to` and
`from` into namespaces that each have a nested `json` command. This makes
it easier to add support for other subcommands in `to` and `from`, and
allows those subcommands to expose settings that only make sense for the
corresponding format. (For example: configuring a catalog for Ion data,
or a list of supported tags for CBOR.)

Also fixes #36 by manually outputting a newline after writing any file
in an Ion text format.

----
_**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**_

### CODE REVIEW

File: src/bin/ion/commands/beta/from/mod.rs
Comment (zslayton) [inline src/bin/ion/commands/beta/from/mod.rs:1]: 🗺️ There are still a LOT of opportunities to DRY up this codebase with some traits to capture the common dispatch logic and base application configuration flags, but they're out of scope for this PR.

File: src/bin/ion/commands/beta/to/json.rs [hunk 1]
```diff
@@ -2,53 +2,37 @@ use anyhow::{Context, Result};
...
                 .short('o')
                 .help("Output file [default: STDOUT]"),
         )
-        .arg(Arg::new("format").index(1).help("Output format"))
         .arg(
-            // Any number of input files can be specified by repeating the "-i" or "--input" flags.
             // Unlabeled positional arguments will also be considered input file names.
             Arg::new("input")
-                .long("input")
-                .short('i')
```
Comment (zslayton) [inline src/bin/ion/commands/beta/to/json.rs:33]: 🗺️ At some point certain subcommands began accepting BOTH `-i` input files and trailing arguments as input files. This is reasonable, but it isn't supported as a first-class feature in `clap`. `clap` has a `debug_assert` that will cause the program to panic in non-`--release` configurations if an option is both named (`-i`, `--input`) and positional.

For now, I'm removing the named flag. We can add it back later, but it will take a bit more code to achieve in the prescribed manner.

File: src/bin/ion/commands/beta/to/json.rs [hunk 2]
```diff
@@ -57,75 +41,44 @@ pub fn run(_command_name: &str, matches: &ArgMatches) -> Result<()> {
                 output_file
             )
         })?;
-        Box::new(file)
+        Box::new(BufWriter::new(file))
```
Comment (zslayton) [inline src/bin/ion/commands/beta/to/json.rs:44]: 🗺️ Previously the `to json` command was not using buffered output except when writing to `STDOUT`.

File: src/bin/ion/commands/beta/to/json.rs [hunk 3]
```diff
@@ -57,75 +41,44 @@ pub fn run(_command_name: &str, matches: &ArgMatches) -> Result<()> {
...
-    // safety guarantees. If the file is unexpectedly truncated while it's being read, for example,
-    // problems could arise.
-    let mmap = unsafe {
-        MmapOptions::new()
-            .map(file)
-            .with_context(|| "Could not mmap ")?
-    };
-
-    // Treat the mmap as a byte array.
-    let ion_data: &[u8] = &mmap[..];
```
Comment (zslayton) [inline src/bin/ion/commands/beta/to/json.rs:114]: 🗺️ `ion-rs` now supports iterating over the elements in a buffered reader, so we no longer have to `mmap` the input file. This also means that we can read directly from `STDIN` without first dumping it to a temporary file.

File: src/bin/ion/commands/beta/to/mod.rs
Comment (zslayton) [inline src/bin/ion/commands/beta/to/mod.rs:1]: 🗺️ Again, lots of opportunity to DRY this up remains.

File: src/bin/ion/commands/dump.rs [hunk 4]
```diff
@@ -95,18 +90,30 @@ pub(crate) fn write_in_format(
     format: &str,
     count: Option<usize>,
 ) -> IonResult<usize> {
-    match format {
+    // XXX: The text formats below each have additional logic to append a newline because the
+    //      ion-rs writer doesn't handle this automatically like it should.
```
Comment (zslayton) [inline src/bin/ion/commands/dump.rs:94]: 🗺️ Addresses #36. The real fix still needs to happen upstream in `ion-rs`. See amazon-ion/ion-rust#437.

**Review by desaikd — APPROVED** [review]
Looks good! It would be nice to have a parent sub command (maybe `convert`) for `from` and `to`. I think that will give us nice encapsulation of the converter commands as well as we could specify some common behavior there but as you mentioned this is out of scope for the PR.

File: src/bin/ion/commands/beta/to/json.rs (hunk 3 above)
Comment (jobarr-amzn) [reply src/bin/ion/commands/beta/to/json.rs:114]: 🎉

File: src/bin/ion/commands/beta/to/json.rs [hunk 5]
```diff
@@ -57,75 +41,44 @@ pub fn run(_command_name: &str, matches: &ArgMatches) -> Result<()> {
...
     };
 
-    if let Some(input_file_iter) = matches.get_many::<String>("input") {
-        for input_file in input_file_iter {
-            let mut file = File::open(input_file)
-                .with_context(|| format!("Could not open file '{}'", input_file))?;
-            convert(&mut file, &mut output, format)?;
+    if let Some(input_file_names) = matches.get_many::<String>("input") {
+        // Input files were specified, run the converter on each of them in turn
+        for input_file in input_file_names {
```
Comment (jobarr-amzn) [inline src/bin/ion/commands/beta/to/json.rs:51]: We see this pattern repeated over and over again in `ion-cli`- in the long term it would be great if we had a common solution to it. Nothing to do here at the moment.

**Review by jobarr-amzn — APPROVED** [review]
